AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for the database resources of the financial budgeting and savings application.

Parameters:
  MasterUsername:
    Type: String
    Description: "Master username for the RDS instance"
    NoEcho: true

  MasterUserPassword:
    Type: String
    Description: "Master user password for the RDS instance"
    NoEcho: true

  DBName:
    Type: String
    Description: "Name of the database to create"
    Default: "budgetapp"

  MinCapacity:
    Type: Number
    Description: "Minimum ACU capacity for Aurora Serverless v2"
    Default: 0
    MaxValue: 128

  MaxCapacity:
    Type: Number
    Description: "Maximum ACU capacity for Aurora Serverless v2"
    Default: 1
    MinValue: 0.5
    MaxValue: 128

  DBSubnetCidr:
    Type: String
    Description: CIDR Block for DB subnet 1
    Default: "10.0.3.0/24"

  DBAV:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for DB subnet 1

  DBSubnetCidr2:
    Type: String
    Description: CIDR Block for DB subnet 2
    Default: "10.0.4.0/24"

  DBAV2:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for DB subnet 2

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref Cidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: budgetapp-prod-vpc

  DBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref DBAV
      CidrBlock: !Ref DBSubnetCidr
      Tags:
        - Key: Name
          Value: budgetapp-prod-db-subnet-1

  DBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref DBAV2
      CidrBlock: !Ref DBSubnetCidr2
      Tags:
        - Key: Name
          Value: budgetapp-prod-db-subnet-2

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: budgetapp-prod-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - key: Name
          Value: bugetapp-prod-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  DBContainerSubnetRouteTableAssocition:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DBSubnet2
      RouteTableId: PublicRouteTable

  RDSInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      VpcId: !Ref VPC
      # The security group ingress rule will be added in infrastructure-stack.yml
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: budgetapp-prod-rds-sg

  AuroraDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "AuroraDBSubnetGroup"
      DBSubnetGroupDescription: "Subnet group for Aurora Serverless v2"
      SubnetIds:
        - !Ref DBSubnet
        - !Ref DBSubnet2
      Tags:
        - Key: Name
          Value: budgetapp-prod-db-subnet-group

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.08.0"
      DatabaseName: !Ref DBName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBClusterIdentifier: !Sub "${AWS::StackName}-aurora-cluster"
      DBSubnetGroupName: !Ref AuroraDBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref RDSInstanceSecurityGroup
      ServerlessV2ScalingConfiguration:
        MinCapacity: !Ref MinCapacity
        MaxCapacity: !Ref MaxCapacity
      EnableHttpEndpoint: true
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: budgetapp-prod-aurora-cluster

  AuroraPrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-mysql
      PromotionTier: 1
      Tags:
        - Key: Name
          Value: budgetapp-prod-aurora-primary

Outputs:
  AuroraClusterEndpoint:
    Description: "Aurora Cluster Endpoint"
    Value: !GetAtt AuroraCluster.Endpoint.Address
  AuroraClusterPort:
    Description: "Aurora Cluster Port"
    Value: !GetAtt AuroraCluster.Endpoint.Port
  DBNameOutput:
    Description: "Database Name"
    Value: !Ref DBName
  RDSInstanceSecurityGroupId:
    Description: "RDS Instance Security Group ID"
    Value: !GetAtt RDSInstanceSecurityGroup.GroupId
  VPCId:
    Description: "VPC ID"
    Value: !Ref VpcId
