
FROM node:20


WORKDIR /app


COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 80

# Command to start the server
CMD ["node", "server.js"]